name: Flutter Build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.10.5'  # Replace with your Flutter version if needed

      - run: flutter pub get
      - run: flutter build apk --release
